image Navi inquiet="images/children_inquiet.png"
image garde lance="images/Garde_Lance.png"
image mechant1="images/Homme_lezard_voleur.png"
image mechant2="images/Homme_lezard_sorcier.png"
image fermier="images/Fermier_triste.png"
image fermier content="images/Fermier.png"